### ISSUE TITLE
Breaks layout of store.steampowered.com

### ISSUE THREAD

**Issue by Keith94** [Hinaser/MultiWindow#5]
https://store.steampowered.com/app/648350/Jurassic_World_Evolution/

![firefox_2018-06-10_17-40-27](https://user-images.githubusercontent.com/5490615/41208204-89b8b5f4-6cd5-11e8-9377-bb82e43ac332.png)

**Comment by Hinaser** [comment]
Where is broken?
I need more details on this issue.

**Comment by Keith94** [comment]
@Hinaser This is how the page I linked above should look normally.

![image](https://user-images.githubusercontent.com/5490615/41259821-e18c30c6-6d89-11e8-97b0-76d12055f42d.png)

But with the add-on installed, it looks broken (like in the first screenshot).
